src/quiz_app/urls.py
from django.urls import path
from . import views


app_name = 'quiz'
urlpatterns = [

    path('', views.index, name='index'),

    path('<int:quiz_id>/', views.single_quiz_page, name='single_quiz_page'),
    path('<int:quiz_id>/<int:question_id>/', views.single_question_page, name='single_question_page'),
    path('<int:quiz_id>/<int:question_id>/vote/', views.vote, name='vote'),
    path('<int:quiz_id>/results', views.results_page, name='results_page'),
    path('create/', views.create_quiz_page, name='create_quiz_page'),
    path('create/<int:quiz_id>/<int:question_id>/', views.create_new_question_page, name='create_question_page'),

]

src/quizwsiz/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('quiz_app.urls')),
]

src/quiz_app/models.py
from django.db import models


class Quiz(models.Model):
    """
    Represents single quiz
    """
    quiz_title = models.CharField(max_length=300)
    num_questions = models.IntegerField(default=0)

    def __str__(self):
        return self.quiz_title


class Question(models.Model):
    """
    Represents single question
    """
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    question_text = models.CharField(max_length=300)
    question_num = models.IntegerField(default=0)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    """
    Represents single question answer choice
    """
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=300)
    correct = models.BooleanField(default=False)

    def __str__(self):
        return self.choice_text

src/quiz_app/forms.py
from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _


class CreateNewQuizForm(forms.Form):
    """
    Form to create a new quiz
    """
    quiz_name = forms.CharField(max_length=30, label="Quiz Name")
    num_questions = forms.IntegerField(label="Number of Questions")

    def clean_name(self):
        """
        Checks if quiz name is unique
        :return: error free data
        """
        data = self.cleaned_data['quiz_name']

        if data == "Default_Name":
            raise ValidationError(_('Invalid name! Quiz name must be unique.'))

        return data

    def clean_num_questions(self):
        """
        Checks if number of questions is a positive integer
        :return: error free data
        """
        data = self.cleaned_data['num_questions']

        if (isinstance(data, int) is False) or (data < 1):
            raise ValidationError(_('Invalid number of questions!'))

        return data


class CreateNewQuestionForm(forms.Form):
    """
    Form to create questions with choices for each quiz
    """
    question_text = forms.CharField(max_length=300, label="Question Text",
                                    widget=forms.TextInput(attrs={'class': 'question_text_box'}))

    choice1_text = forms.CharField(max_length=300, label="Choice 1",
                                   widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice1_correctness = forms.BooleanField(label="Choice 1 Correct?", required=False,
                                             widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice2_text = forms.CharField(max_length=300, label="Choice 2",
                                   widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice2_correctness = forms.BooleanField(label="Choice 2 Correct?", required=False,
                                             widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice3_text = forms.CharField(max_length=300, label="Choice 3",
                                   widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice3_correctness = forms.BooleanField(label="Choice 3 Correct?", required=False,
                                             widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    choice4_text = forms.CharField(max_length=300, label="Choice 4",
                                   widget=forms.TextInput(attrs={'class': 'choice_box'}))
    choice4_correctness = forms.BooleanField(label="Choice 4 Correct?", required=False,
                                             widget=forms.CheckboxInput(attrs={'class': 'choice_correct_box'}))

    def clean(self):
        """
        Makes sure that exactly one answer is selected to be true
        :return: error free data
        """
        choice1_answer = self.cleaned_data["choice1_correctness"]
        choice2_answer = self.cleaned_data["choice2_correctness"]
        choice3_answer = self.cleaned_data["choice3_correctness"]
        choice4_answer = self.cleaned_data["choice4_correctness"]

        answer_list = [choice1_answer, choice2_answer, choice3_answer, choice4_answer]

        print(answer_list)

        trueCount = 0
        for answer in answer_list:
            if answer:
                trueCount += 1

        if trueCount != 1:
            raise ValidationError(_('Must have exactly one correct answer'))

        return self.cleaned_data

src/quiz_app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Quiz, Choice, Question
from .forms import CreateNewQuizForm, CreateNewQuestionForm


def index(request):
    """
    Home page with list of quizzes
    :param request: request object
    :return: render index page with context
    """
    all_quizzes = Quiz.objects.all()
    for quiz in all_quizzes:
        if len(quiz.question_set.all()) == 0:
            quiz.delete()
            all_quizzes = Quiz.objects.all()
    context = {'all_quizzes': all_quizzes,
               'title': 'Quiz WSIiZ'}
    return render(request, 'index.html', context)


def single_quiz_page(request, quiz_id):
    """
    Start page of a particular quiz
    :param request: request object
    :param quiz_id: id of a particular quiz
    :return:
    Number of questions > 0: render single quiz page with context
    Else: render index page with context
    """
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    num_of_questions = len(quiz.question_set.all())

    if num_of_questions == 0:
        quiz.delete()
        all_quizzes = Quiz.objects.all()
        context = {'all_quizzes': all_quizzes}
        return render(request, 'index.html', context)

    quiz.num_questions = num_of_questions
    quiz.save()

    request.session["num_correct"] = 0
    request.session["num_wrong"] = 0

    context = {'quiz': quiz, 'num_questions': num_of_questions}
    return render(request, 'single_quiz_page.html', context)


def single_question_page(request, quiz_id, question_id):
    """
    Question page with answers for a selected quiz
    :param request: request object
    :param quiz_id: id of a particular quiz
    :param question_id: id of a particular question
    :return: render single question page with context
    """
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)
    total = len(quiz.question_set.all())
    percent = ((current_question.question_num - 1)/total)*100

    next_or_submit = "Next"
    last_question_check = False
    if question_id == (len(quiz.question_set.all())):
        last_question_check = True
        next_or_submit = "Submit"

    next_question_id = question_id + 1

    all_choices = current_question.choice_set.all()

    context = {
        'current_question': current_question,
        'all_choices': all_choices,
        'quiz': quiz,
        'next_question_id': next_question_id,
        'last_question_check': last_question_check,
        'next_or_submit': next_or_submit,
        'total': total,
        'percent': percent
    }

    return render(request, 'single_question_page.html', context)


def vote(request, quiz_id, question_id):
    """
    View that receives info from user's answer to question and determines correctness
    :param request: request object
    :param quiz_id: id of a particular quiz
    :param question_id: id of a particular question
    :return:
    No answer chosen: render the same page with error message
    End of a quiz: redirect to results page
    Else: redirect to next question page
    """
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    current_question = quiz.question_set.get(question_num=question_id)
    total = len(quiz.question_set.all())
    percent = ((current_question.question_num - 1)/total)*100

    next_or_submit = "Next"
    if question_id == (len(quiz.question_set.all())):
        next_or_submit = "Submit"

    try:
        selected_choice = current_question.choice_set.get(pk=request.POST['choice'])
    except(KeyError, Choice.DoesNotExist):
        return render(request, 'single_question_page.html', {
            'quiz': quiz,
            'current_question': current_question,
            'error_message': "Choose an answer!",
            'next_or_submit': next_or_submit,
            'total': total,
            'percent': percent
        })
    else:
        correct_answer = current_question.choice_set.get(correct=True)

        if selected_choice == correct_answer:
            request.session["num_correct"] += 1
        else:
            request.session["num_wrong"] += 1

        if question_id == (len(quiz.question_set.all())):
            return HttpResponseRedirect(reverse('quiz:results_page', args=(quiz.id,)))
        else:
            return HttpResponseRedirect(reverse('quiz:single_question_page', args=(quiz_id, question_id + 1)))


def results_page(request, quiz_id):
    """
    Quiz results page
    :param request: request object
    :param quiz_id: id of a particular quiz
    :return: render results page with context
    """
    quiz = get_object_or_404(Quiz, pk=quiz_id)

    num_correct = request.session["num_correct"]
    num_wrong = request.session["num_wrong"]

    total_questions = num_correct + num_wrong

    score = num_correct / total_questions
    score_over_75 = False
    if score >= .75:
        score_over_75 = True
    percentage_score = "{:.0%}".format(score)

    context = {
        'num_correct': num_correct,
        'num_wrong': num_wrong,
        'score_over_75': score_over_75,
        'percentage_score': percentage_score,
        'total_questions': total_questions,
        'quiz': quiz,
    }
    return render(request, 'results_page.html', context)


def create_quiz_page(request):
    """
    Creation page for a quiz
    :param request: request object
    :return:
    Creation page form is valid: redirect to create question page
    Else: render creation page with context
    """
    if request.method == 'POST':

        form = CreateNewQuizForm(request.POST)

        if form.is_valid():
            quiz_name = form.cleaned_data['quiz_name']
            num_questions = form.cleaned_data['num_questions']

            new_quiz = Quiz(quiz_title=quiz_name, num_questions=num_questions)
            new_quiz.save()

            return HttpResponseRedirect(reverse('quiz:create_question_page', args=(new_quiz.id, 1,)))

    else:
        form = CreateNewQuizForm()

    context = {
        'form': form,
        'title': 'Create Quiz'
    }

    return render(request, 'create_quiz_page.html', context)


def create_new_question_page(request, quiz_id, question_id):
    """
    Quiz question creation page
    :param request: request object
    :param quiz_id: id of a particular quiz
    :param question_id: id of a particular question
    :return:
    Create new question form is valid:
        Last question: redirect to index page
        Else: redirect to next question creation page
    Else: render question creation page with context


    """
    quiz = Quiz.objects.get(pk=quiz_id)

    if request.method == 'POST':

        form = CreateNewQuestionForm(request.POST)

        if form.is_valid():

            question_text = form.cleaned_data['question_text']

            choice1 = form.cleaned_data["choice1_text"]
            choice1_correctness = form.cleaned_data["choice1_correctness"]

            choice2 = form.cleaned_data["choice2_text"]
            choice2_correctness = form.cleaned_data["choice2_correctness"]

            choice3 = form.cleaned_data["choice3_text"]
            choice3_correctness = form.cleaned_data["choice3_correctness"]

            choice4 = form.cleaned_data["choice4_text"]
            choice4_correctness = form.cleaned_data["choice4_correctness"]

            question = Question(quiz=quiz, question_text=question_text, question_num=question_id)
            question.save()

            question.choice_set.create(choice_text=choice1, correct=choice1_correctness)
            question.choice_set.create(choice_text=choice2, correct=choice2_correctness)
            question.choice_set.create(choice_text=choice3, correct=choice3_correctness)
            question.choice_set.create(choice_text=choice4, correct=choice4_correctness)

            if question_id == quiz.num_questions:
                return HttpResponseRedirect(reverse('quiz:index'))
            else:
                return HttpResponseRedirect(reverse('quiz:create_question_page', args=(quiz_id, question_id + 1,)))

    else:
        form = CreateNewQuestionForm()

    if question_id == quiz.num_questions:
        next_submit = "Submit"
    else:
        next_submit = "Next"

    context = {
        'form': form,
        'question_num': question_id,
        'next_submit': next_submit,

    }

    return render(request, 'create_question_page.html', context)

src/quiz_app/templates/base.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <title>{{ title }}</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'quiz_app/style.css' %}">
</head>
<body>
<nav  class="navbar navbar-expand-lg bg-dark text-white navbar-dark sticky-top d-flex justify-content-center">
    <a href="/" class=" navbar-brand"><img src="{% static 'quiz_app/logo.png' %}" height="50px" alt=""> Quiz WSIiZ</a>
</nav>
<div class="container-xl pt-1 pb-5 bg-light min-100">
{% block body%}
{% endblock %}
</div>
<footer class="fixed-bottom bg-dark text-white">
    <div class="text-center h5 p-2">Made by <i class="fab fa-github"></i><a href="https://github.com/LipaMar"> LipaMar </a>
        <a href="https://github.com/DowelMartin"> DowelMartin </a>
        <a href="https://github.com/SPiersiak"> SPiersiak </a>
        <a href="https://github.com/SPoweska"> SPoweska </a> 2021 &copy; </div>
</footer>
</body>
</html>

src/quiz_app/templates/create_question_page.html
{% extends "base.html" %}

{% block body %}
<div class="card border-dark my-3">
        <div class="card-body text-center">

        <h1 class="pb-1">Create Question {{ question_num }}</h1>

        <form action="" method="post">
            {% csrf_token %}

            <div class>
                {{ form.question_text.errors }}
                <label  for="{{ form.question_text.id_for_label }}">Question Text:  </label>
                {{ form.question_text }}
            </div>

            <div class="d-flex justify-content-center">

                <div>
                    {{ form.choice1_text.errors }}
                    <label  for="{{ form.choice1_text.id_for_label }}">Choice 1:  </label>
                    {{ form.choice1_text }}
                </div>

                <div>
                    {{ form.choice1_correctness.errors }}
                    <label  for="{{ form.choice1_text.id_for_label }}"></label>
                    {{ form.choice1_correctness }}

                </div>

            </div>


            <div class="d-flex justify-content-center">

                <div>
                    {{ form.choice2_text.errors }}
                    <label  for="{{ form.choice2_text.id_for_label }}">Choice 2:  </label>
                    {{ form.choice2_text }}
                </div>

                <div>
                    {{ form.choice2_correctness.errors }}
                    <label  for="{{ form.choice2_text.id_for_label }}"></label>
                    {{ form.choice2_correctness }}
                </div>

            </div>


            <div class="d-flex justify-content-center">

                <div>
                    {{ form.choice3_text.errors }}
                    <label  for="{{ form.choice3_text.id_for_label }}">Choice 3:  </label>
                    {{ form.choice3_text }}
                </div>

                <div>
                    {{ form.choice3_correctness.errors }}
                    <label  for="{{ form.choice3_correctness.id_for_label }}"></label>
                    {{ form.choice3_correctness }}
                </div>

            </div>


            <div class="d-flex justify-content-center">

                <div>
                    {{ form.choice4_text.errors }}
                    <label  for="{{ form.choice4_text.id_for_label }}">Choice 4:  </label>
                    {{ form.choice4_text }}
                </div>

                <div>
                    {{ form.choice4_correctness.errors }}
                    <label  for="{{ form.choice4_correctness.id_for_label }}"></label>
                    {{ form.choice4_correctness }}
                </div>

            </div>

            <div class="text-danger font-weight-bold text-center pt-2 d-flex justify-content-center">
                {{ form.non_field_errors }}
            </div>


        <input class="submit_button" type="submit" value={{ next_submit }}>
        </form>
</div>
    </div>
{% endblock %}

src/quiz_app/templates/create_quiz_page.html
{% extends "base.html" %}

{% block body %}

    <div class="card border-dark my-3">
        <div class="card-body text-center">

            <h1 class="pb-1">Create Quiz</h1>
            <form action="" method="post">
                {% csrf_token %}
                <div>
                    {{ form.non_field_errors }}
                </div>

                <div>
                    {{ form.quiz_name.errors }}
                    <label class="d-flex justify-content-center" for="{{ form.quiz_name.id_for_label }}">Quiz Name: </label>
                    {{ form.quiz_name }}
                </div>

                <div>
                    <label class="d-flex justify-content-center" for="{{ form.num_questions.id_for_label }}">Number of
                        Questions: </label>
                    {{ form.num_questions }}
                    <div class="text-danger font-weight-bold text-center pt-2 d-flex justify-content-center">
                        {{ form.num_questions.errors }}
                    </div>
                </div>


                <input class="btn btn-outline-success" type="submit" value="Create">
            </form>

        </div>
    </div>
{% endblock %}

src/quiz_app/templates/index.html
{% extends "base.html" %}

{% block body %}
    <div class="mt-2 mb-3">
        <div class="card-body">
            <a class="btn btn-success btn-lg d-flex justify-content-center mx-5" href="{% url 'quiz:create_quiz_page' %}">Create a new quiz</a>
        </div>
    </div>
    {% if all_quizzes %}
        <div class="card-columns text-white">


            {% for object in all_quizzes %}
                {% load colors %}
                <div class="card my-3 bg-{% color forloop.counter0 %}">
                <img class="card-img-top"
                     src="static/quiz_app/quiz.png"
                     alt="Card image cap">
                    <div class="card-body text-center">
                        <h3 class="card-title">{{ object.quiz_title }}</h3>
                        <p>Number of questions: {{ object.num_questions }}</p>
                        <a class="btn btn-light btn-lg d-flex justify-content-center mx-5"
                           href="{% url 'quiz:single_quiz_page' object.id %}">Start</a>
                    </div>
                </div>
            {% endfor %}

        </div>
    {% else %}
        <p>There are no quizzes in the database.</p>
    {% endif %}
{% endblock %}

src/quiz_app/templates/results_page.html
{% extends "base.html" %}

{% block body %}
    <div class="card border-dark my-3">
        <div class="card-body text-center">
            <h3>Your results of {{ quiz.quiz_title }}</h3>
            <p>Number of correct answers: {{ num_correct }}/{{ total_questions }}</p>
            <p> Percentage Result:
                {% if score_over_75 %}
                    <p class="text-success font-weight-bold">{{ percentage_score }}</p>
                    <p class="font-italic">Woohoo! Congratulations, good result.</p>
                {% else %}
                    <p class="text-danger font-weight-bold">{{ percentage_score }}</p>
                    <p class="font-italic">Unfortunately, you failed to pass the Quiz, Please try again.</p>
                {% endif %}
            </p>

            <div class="btn-group" role="group">
                <a class="btn btn-outline-primary" href="{% url 'quiz:index' %}">Home</a>
                <a class="btn btn-outline-success" href="{% url 'quiz:single_quiz_page' quiz.id %}">Try Again</a>
            </div>
        </div>
    </div>
{% endblock %}

src/quiz_app/templates/single_question_page.html
{% extends "base.html" %}

{% block body %}
    <div>
        <div class="card p-2">
            <div class="progress">
                <div class="progress-bar progress-bar-striped progress-bar-animated bg-secondary"
                     style="width:{{ percent }}%" role="progressbar"
                     aria-valuenow="{{ current_question.question_num }}" aria-valuemin="0"
                     aria-valuemax="{{ total }}"></div>
            </div>
            <h2>{{ current_question.question_text }}</h2>

            <div class="d-flex justify-content-center">
                <form action="{% url 'quiz:vote' quiz.id current_question.question_num %}" method="post">
                    {% csrf_token %}
                    {% for x in current_question.choice_set.all %}
                        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ x.id }}">
                        <label for="choice{{ forloop.counter }}">{{ x.choice_text }}</label>
                        <br>
                    {% endfor %}
                    {% if error_message %}<p class="text-danger text-center"><b>{{ error_message }}</b></p>{% endif %}
                    <input class="btn btn-dark" type="submit" value={{ next_or_submit }}>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

src/quiz_app/templates/single_quiz_page.html
{% extends "base.html" %}

{% block body %}
    <div class="card border-dark my-3">
        <div class="card-body text-center">
            <h1>{{ quiz.quiz_title }}</h1>
            <p>Number of questions: {{ quiz.num_questions }}</p>

            <div class="btn-group" role="group">
                <a class="btn btn-outline-primary" href="{% url 'quiz:single_question_page' quiz.id 1 %}">Start Quiz!</a>
                <a class="btn btn-outline-dark" href="{% url 'quiz:index' %}">Back</a>
            </div>
        </div>
    </div>
{% endblock %}